apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: testpmd
  name: el-testpmd
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-testpmd


