apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-client-cluster
  namespace: dpdk-build-testpmd
spec:
  params:
  - default: oc $@
    description: The OpenShift CLI arguments to run
    name: SCRIPT
    type: string
  - default:
    - help
    description: The OpenShift CLI arguments to run
    name: ARGS
    type: array
  - default: default
    description: Name of the project or namespace
    name: NAMESPACE
    type: string
  - default: kubeconfig
    description: kubeconfig file name
    name: FILENAME
    type: string
  steps:
  - args:
    - --kubeconfig
    - $(workspaces.kube.path)/$(params.FILENAME) -n $(params.NAMESPACE)
    - $(params.ARGS)
    image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
    name: oc
    resources: {}
    script: $(params.SCRIPT)
  workspaces:
  - name: kube
